// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-fiu6A_BwB4mvU7Y4UnOjyRdoGy99wuY',
    appId: '1:712191774745:web:eb08eade8c48dc33f15a88',
    messagingSenderId: '712191774745',
    projectId: 'moviesauthroute',
    authDomain: 'moviesauthroute.firebaseapp.com',
    storageBucket: 'moviesauthroute.firebasestorage.app',
    measurementId: 'G-W33QM2VQN2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTr9GAjHFAsZQk7hx5j9ckJlNs5PuHx74',
    appId: '1:712191774745:android:eef4fbb0ea857559f15a88',
    messagingSenderId: '712191774745',
    projectId: 'moviesauthroute',
    storageBucket: 'moviesauthroute.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgSI_pGmAZqF2jaScHTmVNJ20yNvJelAM',
    appId: '1:712191774745:ios:c1d512a35f02099af15a88',
    messagingSenderId: '712191774745',
    projectId: 'moviesauthroute',
    storageBucket: 'moviesauthroute.firebasestorage.app',
    iosBundleId: 'com.example.moviesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgSI_pGmAZqF2jaScHTmVNJ20yNvJelAM',
    appId: '1:712191774745:ios:c1d512a35f02099af15a88',
    messagingSenderId: '712191774745',
    projectId: 'moviesauthroute',
    storageBucket: 'moviesauthroute.firebasestorage.app',
    iosBundleId: 'com.example.moviesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-fiu6A_BwB4mvU7Y4UnOjyRdoGy99wuY',
    appId: '1:712191774745:web:aa62d71448d6b413f15a88',
    messagingSenderId: '712191774745',
    projectId: 'moviesauthroute',
    authDomain: 'moviesauthroute.firebaseapp.com',
    storageBucket: 'moviesauthroute.firebasestorage.app',
    measurementId: 'G-8J9E3B3XRF',
  );
}
